//
//  CapNotifications.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class CapNotifications: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _dateTime: String?
    var _capStatus: String?
    var _pillTaken: String?
    
    class func dynamoDBTableName() -> String {

        return "patchdemo-mobilehub-1419023733-capNotifications"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_dateTime"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_dateTime" : "dateTime",
               "_capStatus" : "capStatus",
               "_pillTaken" : "pillTaken",
        ]
    }
}
