//
//  PatientInfo.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class PatientInfo: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _name: String?
    var _role: String?
    var _schedule: String?
    var _trial: String?
    
    class func dynamoDBTableName() -> String {

        return "patchdemo-mobilehub-1419023733-patientInfo"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_name" : "name",
               "_role" : "role",
               "_schedule" : "schedule",
               "_trial" : "trial",
        ]
    }
}
